#!/bin/bash

: HEADER = <<'EOL'
██████╗  ██████╗  ██████╗██╗  ██╗███████╗████████╗███╗   ███╗ █████╗ ███╗   ██╗
██╔══██╗██╔═══██╗██╔════╝██║ ██╔╝██╔════╝╚══██╔══╝████╗ ████║██╔══██╗████╗  ██║
██████╔╝██║   ██║██║     █████╔╝ █████╗     ██║   ██╔████╔██║███████║██╔██╗ ██║
██╔══██╗██║   ██║██║     ██╔═██╗ ██╔══╝     ██║   ██║╚██╔╝██║██╔══██║██║╚██╗██║
██║  ██║╚██████╔╝╚██████╗██║  ██╗███████╗   ██║   ██║ ╚═╝ ██║██║  ██║██║ ╚████║
╚═╝  ╚═╝ ╚═════╝  ╚═════╝╚═╝  ╚═╝╚══════╝   ╚═╝   ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝  ╚═══╝
        Name: 4. Local Backdoor Admin: Install with Local Backdoor Admin Credentials
 Description: For clients leveraging a rotating backdoor admin system, this script
              gets the locally cached credentials for the uprade process for
              situations where the end user does not have administrative privileges.
              Otherwise, use the policy parameters defined below.
  Parameters: $1-$3 - Reserved by Jamf (Mount Point, Computer Name, Username)
              $4 - Username of an admin account
              $5 - Admin account password
EOL

##
## Parameters and Defaults
##
ADMINNAME=$([ "$4" ] && echo "$4" || echo "breakglass") ## Either provided or use breakglass
ADMINPASS=$([ "$5" ] && echo "$5" || /usr/bin/defaults read /Library/Preferences/tech.rocketman.backdooradmin.plist Password)

## Run upgrade with provided credentials
echo ${ADMINNAME} | '/Applications/Install macOS Big Sur.app/Contents/Resources/startosinstall' --nointeraction --agreetolicense --forcequitapps --user ${ADMINPASS} --stdinpass
